### ISSUE TITLE
Add traits for all queries for `build` and `to_string`

### ISSUE THREAD

**Issue by nitnelave** [SeaQL/sea-query#43]
Can we add a trait for all query types to factor the interface/implementation of `build` and `to_string`? That way, if we want a function that takes any query and a builder and builds the query, we can just be generic over the trait, not each specific query type.

WDYT?

**Comment by tyt2y3** [comment]
Thank you for your suggestion. I am aware of the lack of a unified interface among different Statement builders. The problem is, query statements (DQL & DML) have value bindings but schema statements (DDL) do not.

I'd actually prefer to have the `QueryStatement` enum expose a `build` API and `SchemaStatement` enum expose another, and then impl a set of `Into<QueryStatement>` for `SelectStatement` etc.
