### ISSUE TITLE
Fix inconsistent Ownership of `self` in Builder APIs

### ISSUE THREAD

**Issue by forrest-akin** [SeaQL/sea-query#87]
[`TableCreateStatement`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.TableCreateStatement.html)'s builder methods take a mutable reference to `self`, whereas most others ([`ForeignKeyCreateStatement`](https://docs.rs/sea-query/0.12.8/sea_query/foreign_key/struct.ForeignKeyCreateStatement.html), [`IndexCreateStatement`](https://docs.rs/sea-query/0.12.8/sea_query/index/struct.IndexCreateStatement.html), [`ColumnDef`](https://docs.rs/sea-query/0.12.8/sea_query/table/struct.ColumnDef.html), etc) appear to take full ownership of self. My guess is in the typical use case you already know the structure of what's being built ahead of time such that you can have a single fluent chain of calls to builder methods. This turns out to be very unergonomic (compared to taking a mutable reference) when dynamically building up these statements as you end up with a lot of this

```rust
column_def = if column_schema.primary {
    column_def.primary_key()
} else {
    column_def
};
```

instead of simply

```rust
if column_schema.primary {
    column_def.primary_key()
}
```

Not a huge issue, but I figured I'd raise it anyway as an opportunity to align these APIs or otherwise find out why the current design actually makes more sense.

**Comment by tyt2y3** [comment]
Hi again! You must be generating some dynamic schema. Yes this is a bit unfortunate, because we are facing [the same unergonomicity](https://github.com/SeaQL/sea-schema/blob/6736eec1c1a0ff80c76290b5c265a533bc6b16e5/src/mysql/writer/column.rs#L11) too.

You are right. At least the initial design was, there are `Statement` and `Fragment`, where `Statement` should generally return `&mut Self` and `Fragment` would return `Self`.

So we could save the final take() call for the average user.

```rust
let table = Table::create()
    .table(Char::Table)
    .if_not_exists()
    .col(ColumnDef::new(Char::Id).integer().not_null().auto_increment().primary_key().take())
```

What do you think? After a second thought I am now keen to align all fluent API to return `&mut Self`, but again it is a big breaking change I'd rather delay or avoid.

**Comment by forrest-akin** [comment]
I'm in favor of aligning the APIs, and no better opportunity for a breaking change like v1. I'm worried adding `take()` calls to all of the fragments as shifting the noise elsewhere. I wonder if it's possible for `Statement` methods to take `&mut Fragments` and make the call to `.take()` internally?

**Comment by tyt2y3** [comment]
With that say so, yes we can. We will basically take ownership of all fields and leave the struct in default state.
Sounds like a good idea. It then actually is not breaking on a syntax level!
